create:
	python cli.py --action create --aws-profile $AWS_PROFILE --template-generator $(template)

delete:
	python cli.py --action delete --aws-profile $AWS_PROFILE --template-generator $(template)

update:
	python cli.py --action update --aws-profile $AWS_PROFILE --template-generator $(template)
